### ISSUE TITLE
Please update action.yaml to use Node16

### ISSUE THREAD

**Issue by richb-hanover** [jetli/wasm-bindgen-action#25]
In my project, I'm seeing deprecation warnings about Node12. They look like:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: jetli/wasm-bindgen-action@v0.1.0, actions-rs/cargo@v1

Could you update the `action.yaml` file to use `node16` as described in https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

Thanks!

**Comment by jetli** [comment]
Fixed

**Comment by richb-hanover** [comment]
Thanks for the speedy response!
